// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-GToAYwpjknrXFTXfrJZOzJfLHWFl1kk',
    appId: '1:822034519769:web:89401daf0e8173065110c8',
    messagingSenderId: '822034519769',
    projectId: 'marzo-miros-2b',
    authDomain: 'marzo-miros-2b.firebaseapp.com',
    storageBucket: 'marzo-miros-2b.firebasestorage.app',
    measurementId: 'G-TKD0XXYR65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2baOowoNEV-EYXKQSUSsKyUf7UD6LKLc',
    appId: '1:822034519769:android:490e1080c32d68b25110c8',
    messagingSenderId: '822034519769',
    projectId: 'marzo-miros-2b',
    storageBucket: 'marzo-miros-2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsY3emlYEWeXgDfFKY5YDuEtKYqHUHTqI',
    appId: '1:822034519769:ios:bcefa1978b83e98e5110c8',
    messagingSenderId: '822034519769',
    projectId: 'marzo-miros-2b',
    storageBucket: 'marzo-miros-2b.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2bMoheno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsY3emlYEWeXgDfFKY5YDuEtKYqHUHTqI',
    appId: '1:822034519769:ios:bcefa1978b83e98e5110c8',
    messagingSenderId: '822034519769',
    projectId: 'marzo-miros-2b',
    storageBucket: 'marzo-miros-2b.firebasestorage.app',
    iosBundleId: 'com.example.donutApp2bMoheno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-GToAYwpjknrXFTXfrJZOzJfLHWFl1kk',
    appId: '1:822034519769:web:b0dc8c35fd9568495110c8',
    messagingSenderId: '822034519769',
    projectId: 'marzo-miros-2b',
    authDomain: 'marzo-miros-2b.firebaseapp.com',
    storageBucket: 'marzo-miros-2b.firebasestorage.app',
    measurementId: 'G-TS8HXYDBHY',
  );
}
